// INDEX OF REDUCER ACTION
export default {
  cart: {
    ADD_TO_CART: "ADD_TO_CART",
  },
  product: {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    ADD_PRODUCT: "ADD_PRODUCT",
    // FETCH_PRODUCTS_FROM_DB: "FETCH_PRODUCTS_FROM_DB",
    // FETCH_PRODUCTS_FROM_ELASTICSEARCH: "FETCH_PRODUCTS_FROM_ELASTICSEARCH",
  },
};
